# currently we are using the most basic local planner
TrajectoryPlannerROS:
  meter_scoring: true
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  max_vel_x: 0.5
  min_vel_x: 0.1
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  sim_time: 0.5
